### ISSUE TITLE
error when trying to run starter

### ISSUE THREAD

**Issue by vijayshan** [kamilmysliwiec/nest-typescript-starter#3]
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\svak2\code\node_spikes\nest_starter\node_modules\ts-node\src\index.ts:404:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\svak2\code\node_spikes\nest_starter\node_modules\@nestjs\core\index.js:14:17)
    at Module._compile (module.js:409:26)

**Comment by kamilmysliwiec** [comment]
Hi, 
Fixed
