### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by KatSick** [kamilmysliwiec/nest-typescript-starter#7]
```
src/server.ts (5,5): Property 'listen' does not exist on type 'Promise<INestApplication>'. (2339)
    at getOutput (/Users/ochervak/Projects/nest-typescript-starter/node_modules/ts-node/src/index.ts:307:15)
    at /Users/ochervak/Projects/nest-typescript-starter/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/ochervak/Projects/nest-typescript-starter/node_modules/ts-node/src/index.ts:496:11)
    at Module.m._compile (/Users/ochervak/Projects/nest-typescript-starter/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/ochervak/Projects/nest-typescript-starter/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by KatSick** [comment]
Looks like you need to change `server.ts` with:

```
import { NestFactory } from '@nestjs/core';
import { ApplicationModule } from './modules/app.module';

const app = NestFactory.create(ApplicationModule);
app.then(v => v.listen(3000, () => console.log('Application is listening on port 3000')));
```

**Comment by felquis** [comment]
I found this issue, and it looks similar to the problem I'm facing https://github.com/Microsoft/TypeScript/issues/16772

**Comment by patricknazar** [comment]
try `yarn upgrade ts-node @types/node`. Doing this solved it for me.

**Comment by Jflima92** [comment]
Doing this fixed my issues: 
`npm install --save @types/node@latest ts-node@latest --force`

**Comment by julianmnst** [comment]
Just tried @Jflima92 's solution with no success. Got this error instead:
```

 node index.js

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mpjm/Development/project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mpjm/Development/project/node_modules/@nestjs/core/index.js:14:17)
    at Module._compile (module.js:409:26)
```

Any ideas? Where's @kamilmysliwiec ? I'm really excited about Nest.

**Comment by adrien2p** [comment]
Hey guys, i've made a repository which is a starter kit too https://github.com/adrien2p/nest-js-sequelize
If that can help you to find the problem :)

**Comment by julianmnst** [comment]
Ok I reinstalled the project, had the first problem and then did ``npm install --save @types/node@latest ts-node@latest`` without --force. Then I checked my package.json and saw that one package (don't remember wich) still had the * on it's version. npm suggested a version, I manually wrote it on package.json, npm install again and that solved it.

**Comment by Itrulia** [comment]
fixing `ts-node@2.1.0` and `typescript@2.2.1` fixes it for me.

**Comment by kamilmysliwiec** [comment]
Hi,
Fixed.

**Comment by yeria-t** [comment]
Do not forget to import the decorator ;) 

`import {Headers} from '@nestjs/common';`

**Comment by odobdober** [comment]
src/main.ts:5
import * as tslib_1 from "tslib";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Module.m._compile (node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
